# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ebf36af157b9bb1e3ae0a87709b4ec7f"
application_url = "https://push-down-and-hide-out-of-stock.sincoeec.com"
embedded = true
name = "Sold Out Push Down & Hide"
handle = "advanced-collection-sort"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/webhooks/app/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/webhooks/app/app_subscriptions/update"

  [[webhooks.subscriptions]]
  topics = [ "collections/create" ]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/webhooks/app/collections/create"

  [[webhooks.subscriptions]]
  topics = [ "collections/update" ]
  # include_fields = [ "title", "id", "products_count" ]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/webhooks/app/collections/update"
  
  [[webhooks.subscriptions]]
  topics = [ "collections/delete" ]
  # include_fields = [ "title", "id", "products_count" ]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/webhooks/app/collections/delete"

  [[webhooks.subscriptions]]
  topics = [ "bulk_operations/finish" ]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/webhooks/app/bulk_operations/finish"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/webhooks/app/products/create"
  
  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/webhooks/app/products/update"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/webhooks/app/products/delete"



[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_publications,read_product_listings,read_locations"

[auth]
redirect_urls = [ "https://push-down-and-hide-out-of-stock.sincoeec.com/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "advanced-collection-sort.myshopify.com"
include_config_on_deploy = true
automatically_update_urls_on_dev = false
