FROM node:22.9.0-bullseye-slim
WORKDIR /app

# Copy manifests first for better caching
COPY package.json ./
COPY apps/frontend/package.json apps/frontend/
COPY packages/db/package.json packages/db/
COPY packages/redis/package.json packages/redis/
COPY packages/core/package.json packages/core/
COPY packages/queue/package.json packages/queue/
# copy prisma schema early so postinstall can find it
COPY packages/db/prisma packages/db/prisma

RUN npm install --workspaces --include=dev

# Copy source
COPY . .

# Ensure Prisma client exists
RUN npm run -w packages/db prisma:generate

RUN npm install -g @shopify/cli@latest


ENV PORT=3011
EXPOSE 3011
CMD ["npm","run","dev:frontend"]
