# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ebf36af157b9bb1e3ae0a87709b4ec7f"
application_url = "https://push-down-and-hide-out-of-stock.sincoeec.com"
embedded = true
name = "Sold Out Push Down & Hide"
handle = "advanced-collection-sort"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update", "app/scopes_update", "app/uninstalled" ]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/api/webhooks/apps"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "collections/create", "collections/update", "collections/delete" ]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/api/webhooks/collections"

  [[webhooks.subscriptions]]
  topics = [ "bulk_operations/finish" ]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/api/webhooks/bulk-operations"

  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/update", "products/delete" ]
  uri = "https://push-down-and-hide-out-of-stock.sincoeec.com/api/webhooks/products"




[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_publications,read_product_listings,read_locations"

[auth]
redirect_urls = [ "https://push-down-and-hide-out-of-stock.sincoeec.com/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "advanced-collection-sort.myshopify.com"
include_config_on_deploy = true
automatically_update_urls_on_dev = false
