FROM node:22-alpine
WORKDIR /app

# Copy manifests first for better caching
COPY package.json ./
COPY apps/backend/package.json apps/backend/
COPY packages/db/package.json packages/db/
COPY packages/redis/package.json packages/redis/
COPY packages/core/package.json packages/core/
COPY packages/queue/package.json packages/queue/
COPY packages/shopify-auth/package.json packages/shopify-auth/

# copy prisma schema early so postinstall can find it
COPY packages/db/prisma packages/db/prisma

RUN NODE_ENV=development npm install --workspaces --include=dev && npm --global install nodemon

# Copy source
COPY . .

# Ensure Prisma client exists
RUN npm run -w packages/db prisma:generate

ENV PORT=3012
EXPOSE 3012
# CMD ["npm","run","-w","apps/backend","dev"]
CMD ["npm","run","dev:backend"]
