services:
  # Node.js service for Shopify Remix app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shopify-remix-app
    container_name: advanced_collection_sort_app
    env_file:
      - ./.env.production
    restart: unless-stopped 
    ports:
      - '3011:3011'
    stdin_open: true # Enable interactive input
    command:
      - npm
      - run
      - docker-start
      - --hostname
      - 0.0.0.0
      - --port
      - "3011"

  # Nginx service for reverse proxy and static file serving/
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Mount custom Nginx config
       - ./certbot/conf:/etc/letsencrypt # Mount Certbot config
       - ./certbot/www:/var/www/certbot # Mount Certbot webroot
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt # Mount Certbot config
      - ./certbot/www:/var/www/certbot # Mount Certbot webroot
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email appcadogroup@gmail.com -d push-down-and-hide-out-of-stock.sincoeec.com --agree-tos --non-interactive