export const JOB_NAMES = 
{
  BULK_OPERATION: 'BULK_OPERATION',
  PUSH_DOWN: 'PUSH_DOWN',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',
  PRODUCT_PUBLISH: 'PRODUCT_PUBLISH',
  PRODUCT_UNPUBLISH: 'PRODUCT_UNPUBLISH',
  VARIANT_CREATE: 'VARIANT_CREATE',
  VARIANT_UPDATE: 'VARIANT_UPDATE',
  VARIANT_DELETE: 'VARIANT_DELETE',
};