# FROM node:22-alpine

# EXPOSE 3012

# # Create app directory
# WORKDIR /opt/app

# # Copy only express package.json for install
# COPY ./package*.json ./
# RUN npm install

# # Install app dependencies
# # COPY ./backend ./
# # COPY ./shared ../shared
# # Copy app + shared code
# COPY . .

# # Install nodemon globally for live reloading
# RUN npm install -g nodemon


# # ENV NODE_ENV=production
# RUN npx prisma generate --schema=./shared/prisma/schema.prisma

# RUN npm run dev





